### ISSUE TITLE
When using Apple Pay the paymentIntent is confirmed twice. 

### ISSUE THREAD

**Issue by revolutionaries** [stripe/stripe-payments-demo#101]
This is happening on the demo page and on my code. The second call is rejected with a status 400:

Failed to load resource: the server responded with a status of 400 ()
https://api.stripe.com/v1/payment_intents/pi_xxxxxxxxxxxxx/confirm

Is this due to 'stripe.handleCardPayment' being called after the paymentIntent is successfully confirmed as described here?

https://stripe.com/docs/stripe-js/elements/payment-request-button#complete-payment-intents

Shouldn't 'handleCardPayment' only be called if the paymentIntent status is 'requires_action'?

**Comment by thorsten-stripe** [comment]
@revolutionaries this is a known, and for now expected issue. We decided that when `handleCardPayment` is called on a PaymentIntent that is in succeeded state, we would simply resolve the promise as successful with the succeeded PaymentIntent object, however, yes, you see the network request 400 in the dev tools, but it does not throw a JavaScript error and therefore doesn't affect the integration.

The reason why you need to call confirm initially is to be able to catch whether the collection of credentials via the PRAPI button was successful and then close the browser payment sheet. If you only call `handleCardPayment` you could end up in a scenario where the browser payment sheet blocks the 3D Secure iframe.

Hope that makes sense.

**Comment by revolutionaries** [comment]
@thorsten-stripe thanks for clarifying that.
