### ISSUE TITLE
problem with apple-developer-merchantid-domain-association

### ISSUE THREAD

**Issue by DendoD96** [stripe/stripe-payments-demo#102]
I'm developing an application using vuejs and i am trying to verify my domain with Apple verification file. I have the file in public/.well-known, the problem is the following: running the command `npm run serve` i see the file at mydomain/.well-known/apple-developer-merchantid-domain-association; running `npm run build & serve -s dist` or deploying my app on heroku the file is not raggiungible.

**Comment by thorsten-stripe** [comment]
Please only file issues here that you believe represent actual bugs or feature requests for the Stripe Payments Demo.

If you're having general trouble with your Stripe integration, please reach out to support using the form at https://support.stripe.com/ (preferred) or via email to support@stripe.com.
