### ISSUE TITLE
The Morgan logger is not referenced, can this be removed?

### ISSUE THREAD

**Issue by jcalfee** [stripe/stripe-payments-demo#104]
In [master]

Imports: https://github.com/stripe/stripe-payments-demo/search?q=morgan&unscoped_q=morgan

The only instance of `morgan` is `logger`.  The `logger` is not referenced beyond this instance:
https://github.com/stripe/stripe-payments-demo/blob/b310ffe9d880b3c5d218fef32370312b5a300bb6/server/node/server.js#L13

**Comment by thorsten-stripe** [comment]
Thanks for spotting and reporting! :)
