### ISSUE TITLE
Feature: Implementing a subscription signup & payment flow

### ISSUE THREAD

**Issue by jcalfee** [stripe/stripe-payments-demo#105]
Implement subscriptions based on the stripe guide: https://stripe.com/docs/billing/subscriptions/payment

Following the stripe guide there is a different code path than the current implementation used for product checkout.  It is similar but does involve copying API calls and functionality and adopting it for subscriptions.  Given the security and complexity it would be advantageous to have this as part of your core package.

From what I see, the cart should prevent checkout of mixed items: subscription(s) and product(s) anywhere the checkout is non-atomic.  It should never be possible to pay for a cart where some items succeed and others fail.

If work has been done on this already, I will appreciate a reference.

**Comment by thorsten-stripe** [comment]
Hi James, currently no plans to extend this demo for subscriptions. It is focused on the one-time-payment/guest checkout use case. For Subscriptions, we have a bunch of samples here that you might find helpful: https://github.com/stripe-samples?q=subs
