### ISSUE TITLE
stripe login isn't setting up keys, port stays open

### ISSUE THREAD

**Issue by sgehrman** [stripe/stripe-payments-demo#106]
Trying to do an npm run dev

I did the stripe login, that worked,

Then ran it and got:

you have not configured API keys yet. To do so, run `stripe login` which will configure your API keys from Stripe

did another npm run dev

Error: listen EADDRINUSE: address already in use

you have not configured API keys yet. To do so, run `stripe login` which will configure your API keys from Stripe

I can't get it working at all.  I tried changing the port a few times.

also the postInstall is set for macOS.  I'm on linux, I don't have brew.

I read that I'm suppose to get rid of the --project-name=stripe-payments-demo?

You need to fix your example.  Too confusing.

found out you have to remove the --project-name=stripe-payments-demo
from the stripe listen, but for some reason the port stays open.

**Comment by thorsten-stripe** [comment]
Thanks for reporting this, and sorry for the troubles! It was meant to help with the CLI setup, but it's probably more trouble than help. Thanks for the feedback!

**Comment by thorsten-stripe** [comment]
@sgehrman could you give it a fresh try with the new README instructions and let me know if it works for you?
