### ISSUE TITLE
Wechat Payment failure immediately

### ISSUE THREAD

**Issue by S8Cloud** [stripe/stripe-payments-demo#113]
When choosing Wechat pay, this failure message popped up right after the QR code generated.
```
Oops, payment failed.
It looks like your order could not be paid at this time. Please try again or select a different payment option.
```

**Comment by S8Cloud** [comment]
Trying to trace the reason, after Wechat QR code generated, the API `payment_intents/${paymentIntent}/status` immediately returns status `requires_payment_method` thus  result in the paymentIntent to end.

Is there any solution?

**Comment by thorsten-stripe** [comment]
@S8Cloud thanks for flagging this! I accidentally had defined `requires_payment_method` as an endstatus for the polling function. Will be redeployed in a minute :)

**Comment by thorsten-stripe** [comment]
https://stripe-payments-demo.appspot.com/ has been redeployed and works as expected now on my end. Can you verify if it works for you? You might have to force refresh the page in case your browser caches JS. Thanks again for flagging!
