### ISSUE TITLE
Another PaymentRequest UI is already showing in a different tab or window.

### ISSUE THREAD

**Issue by ajlond123** [stripe/stripe-payments-demo#114]
Is there anyway to catch the console error shown when trying to open the PaymentRequest UI in another tab?

The error shown is 

> Another PaymentRequest UI is already showing in a different tab or window.

It would be useful to be able to handle this by catching the error and showing a message to the user. 

Maybe something like `paymentRequest.show().catch((error) => { // handle error })`.

**Comment by thorsten-stripe** [comment]
Stripe Elements wraps the Payment Request API and calls show under the hood when the Payment Request Button Element is clicked. You can however implement your own custom button in which case you would call show in your code: https://stripe.com/docs/stripe-js/elements/payment-request-button#html-js-own-button

**Comment by ajlond123** [comment]
I'm not sure what you mean. I've tried implementing a custom button but `paymentRequest.show()` doesn't return any errors. 

`
 const paymentRequest = stripe.paymentRequest({
            country: 'GB',
            currency: 'gbp',
            total: {
                label: 'Example',
                amount: '£99.99',
            },
            requestPayerName: true,
            requestPayerEmail: true,
        });

const btn = document.querySelector('#payment-btn');

btn.addEventListener('click', () => {
    try {
        this.paymentRequest.show();
        } catch (error) {
            console.log('Error ', error);
        }
});
`

In the example above the error isn't caught and instead is outputted to the developer console. So if Stripe is a wrapper around the Payment Request API then it should be possible to capture this error. Either by using Stripe elements or by implementing a custom button as suggested by you. 

What am I missing? Or is it not possible to actually catch this error using Stripe?

**Comment by thorsten-stripe** [comment]
As this doesn't affect this repository specifically, please reach out to support using the form at https://support.stripe.com/ (preferred) or via email to support@stripe.com.

**Comment by zhdanouskikh** [comment]
the exception comes from paymentApi, which is incapsulated in stripe.
so there is no way to handle exceptions that come from paymentRequest.show()

guess paymentRequest.show() should return promise where we can subscribe on catch
