### ISSUE TITLE
Bug - On 3d authentication failure if you press back button it will reload the page.

### ISSUE THREAD

**Issue by usman10scorpio** [stripe/stripe-payments-demo#123]
Hi 

This is interesting. On stripe checkout [demo ](https://checkout.stripe.com/pay/ppage_1GIamvFKnpzPB0MXnca4e9yu#fidkdWxOYHwnPyd1blpxYHZxWm9CPHY2XUhhVm9fQzxOYWgwYjA8f2lcYScpJ3dgY2B3d2B3SndsYmxrJz8nbXFxdXY%2FKip2cXdsdWArZmpoJyknaWpmZGlgJz9rcGlpKSdobGF2Jz9%2BJ2JwbGEnPyc2YDAwNGFnZCg1Z2M8KDE1MjYoPGFmPChnNzZhZz03Njc8YTMnKSdocGxhJz8nNDQ8Y2ZjY2YoMTVhNigxYD08KDw2MDYoMzUxMjZnPDFnYDM8JykndmxhJz8nMTYxYTVgMWcoNTUwZCgxZDAwKGdhMj0oPWcyNWZkM2EyNWA9J3gpJ2dgcWR2Jz9eWHgl)add this card 4000 0000 0000 3220 and make the payment fail and after that hit the back button of browser. It will reload the page for the first time, and after reload, you again try to hit the back button it will take you back to previous page.

What is this behavior. Why it does not take us back for the first time ?

**Comment by thorsten-stripe** [comment]
This project does not use Checkout.

Please only file issues here that you believe represent actual bugs or feature requests for the Stripe Payments Demo.

If you're having general trouble with your Stripe integration, please reach out to support using the form at https://support.stripe.com/ (preferred) or via email to support@stripe.com.
