### ISSUE TITLE
[Feature Request] Return existing payment method during createPaymentMethod (or similar languages/methods) if any

### ISSUE THREAD

**Issue by cperonneaud** [stripe/stripe-payments-demo#124]
Hi there,

This request is a follow up on the closed topic :
https://github.com/stripe/stripe-payments-demo/issues/45

I've read the replies from the Stripe Support and this makes no senses for most online shops in my opinion.

1) Why don't we save the card on our server?
For security purpose of course. Card data is super sensitive and it's much more secure to let Stripe handle the protection of the card's data for small businesses. Having multiple websites storing customers' cards increase the risks of their cards being found. The fewer websites having those data, the safer for the customer.

2) Why does the customer uses the same card number?
In our case, it's because we don't save the stored data. But in the case of the previous topic, the reply from the staff does not make sense to me. If the customer updated his payment method, it should be a new card, so the fingerprint, exp month and exp year will be different. Even if the customer ended up using the same card, if your create functions had the requested feature, no duplicate would be created and the existing one would be returned with the existing id. So no problem.

When our customers order several times on our website, their cards are duplicated. We ended up with dozens of identical payment methods. The current solution is to load all the existing payment methods of the customer and compare the fingerprint, exp month and exp year which partially does the trick but with drawbacks:
1) More API calls to get the necessary data meaning customers wait longer
2) We need to delete the duplicate method after it's been created, another unnecessary call if it was handled better.

In the end, the best solution would be the requested feature I think. When sending card data, Stripe should compare the fingerprint, month and year themselves before creation and return the existing payment if any. I'm aware a create function should just create stuff but adding the check in the create functions would keep the current Stripe documentation valid and prevent any additional steps from users.

I don't have a full picture of the Stripe API so if there is any reason this doesn't make sense, let me know.

Best regards

Clement Peronneaud

**Comment by thorsten-stripe** [comment]
Thanks for the feedback, Clement, as mentioned on the other thread, it has been noted and will be taken into consideration for future updates.

Please only file issues here that you believe represent actual bugs or feature requests for the **Stripe Payments Demo**.

For the integration specific issues outlined above, please reach out to support using the form at https://support.stripe.com/ (preferred) or via email to support@stripe.com.
