### ISSUE TITLE
Unable to load demo

### ISSUE THREAD

**Issue by sgwifi** [stripe/stripe-payments-demo#127]
Hi,

I am very new to Stripe programming.

I have copied the files onto my online server and ran it under Apple Safari, but encountered the following errors:

Failed to load resource: the server responded with a status of 404 (Not Found) https://domain.com/products

Failed to load resource: the server responded with a status of 404 (Not Found) https://domain.com/config

Unhandled Promise Rejection: SyntaxError: The string did not match the expected pattern. store.js:73

Unhandled Promise Rejection: IntegrationError: Invalid value for Stripe(): apiKey should be a string. You specified: undefined.

As such, I can only see the header bar (Stripe Payments Demo & View on GitHub), I am unable to view the Shipping & billing information, Payment information, Order summary and the sample products like https://stripe-payments-demo.appspot.com and unable to continue.

Would appreciate any advise on the above issue.

Thanks!

**Comment by thorsten-stripe** [comment]
Hi @sgwifi, you might find it easier getting started with Stripe Checkout, you can find a list of examples here: https://github.com/stripe-samples?q=checkout&type=&language=

In any case, I'm afraid we can't provide support for individual integrations on this repository, for this please reach out to support using the form at https://support.stripe.com/ (preferred) or via email to support@stripe.com.
