### ISSUE TITLE
Missing Flask route

### ISSUE THREAD

**Issue by dramirez-tc** [stripe/stripe-payments-demo#128]
There is a Flask route that's missing and preventing web domains from being added to the Stripe portal for Apple Pay.  

I have a local branch that fixes the issue, but I can't seem to create an remote branch and submit a PR.

**Comment by thorsten-stripe** [comment]
Thanks for flagging @dramirez-tc! Can you add a PR via your own Fork: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork?

**Comment by dougramirez** [comment]
Done!

https://github.com/stripe/stripe-payments-demo/pull/129

**Comment by thorsten-stripe** [comment]
Thanks @dougramirez 
Fixed in #129
