### ISSUE TITLE
Server-based Intents

### ISSUE THREAD

**Issue by dougramirez** [stripe/stripe-payments-demo#130]
We have a unique use case where the setup of an Intent and confirmation are preferably server-side.  It allows us to maintain a store of a mapping of "internal" tokens with actual Stripe Payment Methods and a ledger of payment activity.  And, it lets the card details traverse the public Internet out-of-band from server-side processing to be tokenized directly with Stipe.

I have a branch that supports it.  Would anyone be interested in seeing it implemented in server/python?  Perhaps implemented as a feature toggle.

**Comment by thorsten-stripe** [comment]
@dougramirez are you referring to the manual confirmation flow: https://stripe.com/docs/payments/accept-a-payment-synchronously ?

If your project is public, feel free to link it here so folks can find it :) Thanks

**Comment by dougramirez** [comment]
@thorsten-stripe Sort of.  This adds a server-side endpoint to allow the Intent to be confirmed as part of the checkout flow

https://github.com/dougramirez/stripe-payments-demo/commit/ca421a26baac9ae0fdfbe3cf5fc04e382ec4009f?diff=split

**Comment by thorsten-stripe** [comment]
Thanks @dougramirez. It sounds like more of an edge case, but thanks for sharing :)
