### ISSUE TITLE
"Processing order" button is still visible after successful payment

### ISSUE THREAD

**Issue by connecteev** [stripe/stripe-payments-demo#131]
This is a bug in the Stripe Payments Demo.
Go to https://stripe-payments-demo.appspot.com/

Enter your name and credit card details. After successful payment, you see a "Thanks for your order" success message, but the "Processing order" button is still visible. 
Screenshot: https://www.webpagescreenshot.info/#v2=2LWMvJ1hp

**Comment by thorsten-stripe** [comment]
I'm not able to reproduce this:
![image](https://user-images.githubusercontent.com/23213994/86316309-0335e480-bc5f-11ea-9dab-e66c71dfff58.png)

Can you add your system information?

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
