### ISSUE TITLE
HTTP 400 error when confirming payment request while using payment request button

### ISSUE THREAD

**Issue by mmoore99** [stripe/stripe-payments-demo#133]
When running the demo and using the payment request button to complete a payment I notice in the Chrome Dev Tools that there is a http call that results in an error every time the transaction is completed.

The http command is:
`POST https://api.stripe.com/v1/payment_intents/pi_1GlOkbLqkZN1XDm1205gTdth/confirm `

The error that is returned is:
`{error: {code: "payment_intent_unexpected_state",…}}
error: {code: "payment_intent_unexpected_state",…}
code: "payment_intent_unexpected_state"
doc_url: "https://stripe.com/docs/error-codes/payment-intent-unexpected-state"
message: "You cannot confirm this PaymentIntent because it has already succeeded after being previously confirmed."
payment_intent: {id: "pi_1GlOkbLqkZN1XDm1205gTdth", object: "payment_intent", amount: 2596, canceled_at: null,…}
type: "invalid_request_error"`

This seems to come from the following command in payments.js:
` // Let Stripe.js handle the rest of the payment flow, including 3D Secure if needed.
      const response = await stripe.confirmCardPayment(
        paymentIntent.client_secret
      );`

This doesn't seem to cause a problem as the transactions seems to complete successfully, but is in correct that this error condition exists? Also, I am developing an app using this same approach and am receiving the same error condition.

**Comment by thorsten-stripe** [comment]
Hey @mmoore99, yes, this is the recommended approach to be able to easily handle 3D Secure authentication if required: https://stripe.com/docs/stripe-js/elements/payment-request-button#html-js-complete-payment

Stripe.js graciously handles the request error, so you don't need to be concerned about it.
