### ISSUE TITLE
SSL not enabled when running npm run react

### ISSUE THREAD

**Issue by kopax** [stripe/stripe-payments-demo#134]
I am looking on a webview example to integrate stripe in an expo sdk36 react native application.

Does the react stripe-js checkout example needs SSL? 

Because `npm run react` open the form in http://localhost:3000

**Comment by thorsten-stripe** [comment]
Please only file issues here that you believe represent actual bugs or feature requests for the Stripe Payments Demo.

If you're having general trouble with your Stripe integration, please reach out to support using the form at https://support.stripe.com/ (preferred) or via email to support@stripe.com.

**Comment by kopax** [comment]
The server demo in java is outdated, see https://stackoverflow.com/questions/62247276/stripe-example-java-server-in-spring-boot-incompatible-types-optionalstripeo

I am just trying to get those points resolved globally
