### ISSUE TITLE
Cannot run the java demo with the react application => blank form

### ISSUE THREAD

**Issue by kopax** [stripe/stripe-payments-demo#135]
I want to test the java server provided by stripe payments demo instead of the nodejs one, the code is hosted here:

https://github.com/stripe/stripe-payments-demo/tree/add-react-client/server/java

This is what I am doing:

```bash
git clone https://github.com/stripe/stripe-payments-demo.git
cd stripe-payments-demo
git checkout add-react-client
``` 

I want to test with the react-client (Instead of the vanillajs client), so I do

    sed -i s/vanilla/react-cra\/build/g  server/java/src/main/java/app/Application.java

I first build the react client with:

```
cd client/react-cra
npm run build
cp -R ../vanilla/images build # this is necessary because product images doesn't exist in react client and are required within the page.;
```

After this being done, I compile and run with:

```
cd server/java
gradle build
gradle shadowJar
java -jar build/libs/salesPaymentDemo-1.0-SNAPSHOT.jar

```

This is what I have on my screen:

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/qoWtY.png

The content is white but the html content of the form exist, what I am doing wrong to run the java demo server with the react js demo client?

**Comment by thorsten-stripe** [comment]
@kopax I'm afraid the React client for this demo is a work in progress and not in a stable condition. Unfortunately there currently aren't any plans to complete it. Please refer to https://github.com/stripe-samples/react-elements-card-payment for a React Stripe Elements example.

**Comment by kopax** [comment]
Well, I am very glad to know that. 

I did not get that indication from the stripe website nor the readme, I had to ask here. Would you mind adding those kinds of information on a per report basis to avoid time wasted on people that get started with stripe integration?

**Comment by thorsten-stripe** [comment]
@kopax the `add-react-client` branch is part of the https://github.com/stripe/stripe-payments-demo/pull/115 which is labeled as [WIP], I'm sorry that this gave you the impression of a functioning feature branch! :(

The functionality on the `master` branch should work as expected though. Sorry again that this wasn't clear!
