### ISSUE TITLE
Stripe React Native: handle subscriptions  

### ISSUE THREAD

**Issue by hamzaDv** [stripe/stripe-payments-demo#136]
I'm stuck on this issue: 
When I try to submit this subscription, I got an error of "subscription_payment_intent_requires_action", should I handle it on client-side or there is another way to do it?

For information: I already created setupIntent (verify 3D Secure) and return payment_method

Steps: 
1 - create setupIntent 
2 - generate payment_method ( verify 3D Secure)
3 - create Customer and attach payment_method to it
4 - create Subscription (on back_end) => error: "subscription_payment_intent_requires_action" shows up!

Thank you all!

// Create Subscription With Payment Method + Customer ID
router.post('/createSubscription', function (req, res){
  const {payment_method, customerId} = req.body;
  var stripe = require("stripe")(stripe_sk);
  try{
  stripe.subscriptions
  .create({
    customer: customerId,
    items: [{
      plan: 'plan_HTGCI8ljPYFTHQ'
    }],
    default_payment_method: payment_method,
    expand: ["latest_invoice.payment_intent"],
    // enable_incomplete_payments: true
  }).then(subscription => {
    res.send({
      subscription : subscription
    })
  }).catch(err => {
    res.send({
      err
    })
  })
} catch (error) {
  res.send("Error : ", error);
}
});

**Comment by thorsten-stripe** [comment]
Potentially related to old API version: https://stripe.com/docs/upgrades#2019-03-14

Please only file issues here that you believe represent actual bugs or feature requests for the Stripe Payments Demo.

If you're having general trouble with your Stripe integration, please reach out to support using the form at https://support.stripe.com/ (preferred) or via email to support@stripe.com.

If you have quick code questions I recommend checking out #stripe on Freenode (IRC). A lot of Stripe users and developers hang out there, we're happy to help and answer questions! If you need a client, you can try https://webchat.freenode.net/

**Comment by hamzaDv** [comment]
Thank you for help is there any particular channel to chat to you
