### ISSUE TITLE
complete demo code for alipay

### ISSUE THREAD

**Issue by hkbluesky** [stripe/stripe-payments-demo#139]
Hi, could you provide the complete demo code for alipay including the front-end and back-end?
This demo does not provide the complete demo code for alipay. Thanks

**Comment by thorsten-stripe** [comment]
Hey @hkbluesky, sorry that you weren't able to find the relevant pieces for Alipay, they are included:

1. https://stripe.com/docs/sources/alipay#create-source ➡️ https://github.com/stripe/stripe-payments-demo/blob/master/public/javascripts/payments.js#L363
1. https://stripe.com/docs/sources/alipay#customer-action ➡️ https://github.com/stripe/stripe-payments-demo/blob/master/public/javascripts/payments.js#L443-L447
1. https://stripe.com/docs/sources/alipay#charge-request ➡️  https://github.com/stripe/stripe-payments-demo/blob/master/server/node/routes.js#L133-L151
1. https://stripe.com/docs/sources/alipay#charge-confirmation ➡️ https://github.com/stripe/stripe-payments-demo/blob/master/server/node/routes.js#L113-L131

For further help with your integration, please ask questions via our email support or the technical chat on IRC: https://support.stripe.com/

**Comment by hkbluesky** [comment]
Thanks. I examined the code before I asked. But I think the demo does not work for alipay. I set sourceData per your document.   
https://github.com/stripe/stripe-payments-demo/blob/master/public/javascripts/payments.js#L319-L334
const sourceData = {
                  type: 'alipay',
                  amount: 1,
                  currency: 'usd',
                  redirect: {
                    return_url: 'https://shop.example.com/crtA6B28E1',
                  },
                } 
However, in https://github.com/stripe/stripe-payments-demo/blob/master/public/javascripts/payments.js#L414, the source has a null value. Could you check? Thanks
