### ISSUE TITLE
Pending stripe payment until bank account info is provided

### ISSUE THREAD

**Issue by zahid1123** [stripe/stripe-payments-demo#18]
Hi!
I am facing the issue:

> stripe.error.InvalidRequestError: Request req_owgQt8DxA7ismN: Can only apply an application_fee when the request is made on behalf of another account (using an OAuth key, the Stripe-Account header, or the destination parameter).

This happening because receiver didnt have provided bank account details.

I want to know if there is a way that a "user A" sends payment to "user B" using stripe. At that moment, User B didn't provided bank account details, but stripe deducts the amount from User A account and preserve it until user B add bank information. 
(Just like freelancer.com do, that payment is deducted and can be receive at any time when user enters bank details)

**Comment by thorsten-stripe** [comment]
To use an application fee[0], the request must be made on behalf of another account, using the Stripe-Account header, an OAuth key, or the destination parameter. For more information, see Collecting application fees[1].

[0] https://stripe.com/docs/api#create_charge-application_fee
[1] https://stripe.com/docs/connect/direct-charges#collecting-fees

**Comment by zahid1123** [comment]
Can you help me to figure out how can I make sure that the request is made on the behalf of another account?

**Comment by thorsten-stripe** [comment]
@zahid1123 you have two options, either create the charge directly on a connected account by setting their account ID in the account header[0], or you can pass their account ID as the destination account in the charge creation[1]. The difference between the approaches is explained here: https://stripe.com/docs/connect/charges#choosing-approach

Note that in both cases the account needs to be connected to your platform application, either via OAuth flow[2], or by creating the account through your platform account[3].

If you're still facing issues with this, please reach out to our support engineering team via the form: https://support.stripe.com/email

[0] https://stripe.com/docs/connect/authentication#authentication-via-the-stripe-account-header
[1] https://stripe.com/docs/connect/destination-charges
[2] https://stripe.com/docs/connect/standard-accounts#oauth-flow
[3] https://stripe.com/docs/connect/custom-accounts

**Comment by zahid1123** [comment]
Got it. Thank you so much.

**Comment by heymartinadams** [comment]
Hi @thorsten-stripe, does this mean that when we use the “[separate charges and transfers](https://stripe.com/docs/connect/charges#choosing-approach)” approach (some users may not have signed up with Stripe yet at the time of transaction), we cannot use the `application_fee` feature?

**Comment by heymartinadams** [comment]
Looks like the `application_fee` indeed only works for [Direct Charges](https://stripe.com/docs/connect/charges#direct-charges).
