### ISSUE TITLE
iOS 11.1.1 Safari issue with Stripe Elements Credit Card Field

### ISSUE THREAD

**Issue by dademaru** [stripe/stripe-payments-demo#19]
Hello,

I'm having a issue on **iOS 11.1.1.** on iPhone.
Only in **Safari** (in Chrome or Firefox it works), Stripe Credit Card field doesn't work, both **inline** or with **separate** fields.

I've tried with **WooCommerce Stripe** extensions, on Storefront (WC official theme).
WP 4.9.6, WC 3.4.2, WC Stripe Gateway 4.1.7, Storefront 2.3.2

https://imgur.com/ekTOPy4

The **Credit Card field** appears **collapsed**.
If I click on it, the page **scroll to top** and the cursor is focused at the beginning on an **invisibile field** (`.CardField-number` inside `__privateStripeFrame4` `iframe`) and the iOS number keyboard is shown. You can enter numbers but they are hidden in the invisible field, so it's totally unusable!

https://imgur.com/DsTiyk1

I've tried to uncheck '_Inline Credit Card Form_' setting, but the issue is almost same:

https://imgur.com/SBREkOb

I've then tried [Stripe Official demo](https://stripe.github.io/elements-examples/) and same issue (if I click on the input field, page scrolls to top, hidden field, …):

https://imgur.com/zeS3jck

As I wrote, on Firefox or Chrome on same iOS version, it works.
It also works on iOS 11.4 Safari.
But I'm worried about previous iOS version, since you can't force your customers to update to latest iOS version on their devices and this issue makes Stripe Payment not usable on mobile (at least on iOS Safari).

Thanks

**Comment by toddgibson** [comment]
I am seeing this same issue as reported above.  Are there any updates to this?

**Comment by toddmyphoto** [comment]
Another Todd here, also seeing this same issue using react-stripe-elements. Any solutions?

**Comment by thorsten-stripe** [comment]
Please note that this issue tracker is for bugs or issues directly related to this project, and not for general support. Please feel free to reach out to https://support.stripe.com/email and we would be glad to help further!

Please do feel free to post the resolution here, though, if you've come to a conclusion. Thanks.

**Comment by orangevinz** [comment]
Hi,

You can force the overflow on the .stripe class like that.
It worked for me.

`.stripe {
    overflow: visible!important;
}`
