### ISSUE TITLE
Webhook Confusion

### ISSUE THREAD

**Issue by jakecjones** [stripe/stripe-payments-demo#21]
When I start the app and go to the {###}.ngrok.io/webhook site to test the webhook I get the "Cannot GET /webhook" error.  I created an endpoint in Stripe, clicked to reveal the code, and added that to my .env file after the "STRIPE_WEBHOOK_SECRET=" section. Is there a reason that the webhook is still not working? The second URL does work but the main site I added this to does not. The site I created to test this on is https://payments.bahlrdev.com/. Thanks in advance for your help!

**Comment by thorsten-stripe** [comment]
Sorry for the delay. The `/webhook` route only supports POST requests, therefore you can't access it via the browser GET request.

Please note that this issue tracker is for bugs or issues directly related to this project, and not for general support. Please feel free to reach out to https://support.stripe.com/email and we would be glad to help further!
