### ISSUE TITLE
checkCanMakePayment Request Returns True on Safari Private Window

### ISSUE THREAD

**Issue by arnold-lei** [stripe/stripe-payments-demo#23]
I am running into an issue where a user without Apple Pay enabled is getting Apple Pay if they use Safari Private Window. 

I am making the `canMakePayment()` call and it is returning an object with `{applePay: true}`

Is anyone else running into this issue? Is this something that will be fixed?

**Comment by thorsten-stripe** [comment]
Sorry for the delay, I hope you were able to find a resolution in the meantime.

Please note that this issue tracker is for bugs or issues directly related to this project, and not for general support. Please feel free to reach out to https://support.stripe.com/email and we would be glad to help further!
