### ISSUE TITLE
error

### ISSUE THREAD

**Issue by redbeard2** [stripe/stripe-payments-demo#24]
Running the server 3000
⚠️  Products have already been registered.
Delete them from your Dashboard to run this setup.
⚠️  Setup already in progress.

he stays in a loop nmot showing on the page it self

**Comment by thorsten-stripe** [comment]
The demo is very tightly coupled to the three products we're creating in the setup script. If you're modifying the amount of products being used, there are two locations you need to change:

* Setup script: https://github.com/stripe/stripe-payments-demo/blob/master/server/node/setup.js
* Product setup check: https://github.com/stripe/stripe-payments-demo/blob/master/server/node/routes.js#L191-L198

If you want to use the demo as is, simply create a new Stripe account and use those keys. The setup will run successfully then.
