### ISSUE TITLE
Status of Order is not updated, only tracked in metadata.status

### ISSUE THREAD

**Issue by mccare** [stripe/stripe-payments-demo#27]
In the current implementation the status of the order is tracked in metadata.status. So if you have shippable items, you cannot transition the order into status fullfilled.

I would expect the sample to correctly transition the order to "paid" when the order is paid. This allows me to send emails on order change and also keep track of the shipping tracking information.

Maybe some documentation on how this could be achieved would suffice. 

Right now the order stays in status "created" and cannot transition from there (not via API not via dashboard). 

For CC payments you can call 
```stripe.orders.pay(orderId, { source_id} );```

**Comment by thorsten-stripe** [comment]
We were using the orders API to automatically calculate order amounts from SKUs and not having to use a DB. However the order API does not support non-card payment methods, therefore we were using the metadata to track the status. With PR #48 all references to the orders API have been removed and PaymentIntents[0] are used for status tracking. Thanks for flagging this and sorry for acknowledging this so late!

[0] https://stripe.com/docs/payments/payment-intents
