### ISSUE TITLE
Google Pay does not work on desktop browsers

### ISSUE THREAD

**Issue by evgenyus** [stripe/stripe-payments-demo#29]
I am logged in into Google and have Google Pay payment methods set up on all my browsers, desktop and mobile.

The expected behavior for demo site is to allow for selection between Google Pay or cards stored on the device.

However, on desktop browsers button only shows up when I have card stored in the browsers. It does not allow me to select my Google Pay card.

On mobile Chrome, button shows up even if I have no card stored on the device. It allows me to proceed with Google Pay.

**Comment by thorsten-stripe** [comment]
@evgenyus as it stands today the Stripe PRAPI Element relies on the payment request API for access to Google Pay which is currently no supported on desktop. If you want to make Google Pay available to your customers across desktop browsers you will need to separately integrate Google's pay.js library as outlined here: https://developers.google.com/pay/api/web/guides/tutorial 

Hope this helps, Best,
Thor
