### ISSUE TITLE
I don't have all the striping functions

### ISSUE THREAD

**Issue by lephenix1234** [stripe/stripe-payments-demo#34]
I have just : elements: ƒ, createToken: ƒ, createSource: ƒ, retrieveSource: ƒ, paymentRequest:

**Comment by thorsten-stripe** [comment]
@lephenix1234 are you instantiating Stripe with the PaymentIntent beta flag[0]?

[0] https://github.com/stripe/stripe-payments-demo/blob/master/public/javascripts/payments.js#L30

**Comment by thorsten-stripe** [comment]
See also: https://stripe.com/docs/payments/payment-intents/quickstart#elements
