### ISSUE TITLE
Store.getOrderTotal() returns subunits yet, paymentRequest() errors out

### ISSUE THREAD

**Issue by bjayaram** [stripe/stripe-payments-demo#38]
I am trying to replicate the client side code using google apps script and this code doesn't work for me -I am at a loss to understand why.

`// Create the payment request.`
`  const paymentRequest = stripe.paymentRequest({`
`    country: config.stripeCountry,`
`    currency: config.currency,`
`    total: {`
`      label: 'Total',`
`      amount: store.getOrderTotal(),`
`    },`
....

I am getting the following error:

Error: Invalid value for paymentRequest(): total.amount should be an amount in the currency's subunit. You specified: 2000.

**Comment by thorsten-stripe** [comment]
Please note that this issue tracker is for bugs or issues directly related to this project, and not for general support. Please feel free to reach out to https://support.stripe.com/email and we would be glad to help further!

**Comment by cooperd** [comment]
@bjayaram did you managed to solved this issue?

**Comment by bjayaram** [comment]
Yes, I got it to work but I am not using google apps script for my solution anymore - I decided to do it with javascript.
