### ISSUE TITLE
Google Pay not show in Mobile APP Webview

### ISSUE THREAD

**Issue by anialamo** [stripe/stripe-payments-demo#44]
Hi! When I am testing the Request payment button in my application... from Chrome desktop this works!!!! from Chrome Mobile also it works!!! 
Also I add some view of result in the code, 

My code to show Payment request button is like this:
```
paymentRequest.canMakePayment().then(function(result) { 

        var text = objToString(result);

        var enablingText = '';

        if (result) {

            enablingText = "ENABLED PAYMENT BUTTON !!!";

            prButton.mount('#payment-request-button');

        } else {

            enablingText = "DISABLED PAYMENT BUTTON !!!";

            document.getElementById('payment-request-button').style.display = 'none';

        }

        displayHtmlShow("window.paymentRequest.canMakePayment result: <br>"+text+"<br>"+enablingText);

```
In Desktop Chrome it works fine!!!! In Mobile Chrome it also works fine!!! 
Example with Pay now button and my own logs with result:
![image](https://user-images.githubusercontent.com/35197781/52561257-273f1e80-2dfb-11e9-8885-fb94987a4c60.png)

But When I use a webview that my app mobile call this and open the Internal mobile navigator, in my Samsung Android  this does not work... and in Iphone this also does not work... because this code prints EMPTY result... 
![image](https://user-images.githubusercontent.com/35197781/52561454-bd734480-2dfb-11e9-8798-ce4e4ff92dfb.png)

This means... in a webview called from my app mobile this will not work and only it will be available the Stripe payment button if this is implemented in native?
Thanks!
Ani

**Comment by thorsten-stripe** [comment]
Please note that this issue tracker is for bugs or issues directly related to this project, and not for general support. Please feel free to reach out to https://support.stripe.com/email and we would be glad to help further!

Do feel free to post the resolution here, though, if you've found it. Thanks.

**Comment by diachedelic** [comment]
I too would like to know if the Payment Request Button is expected to work in a WebView environment, specifically for Google Pay. I can't find any info on it in the docs.

**Comment by thorsten-stripe** [comment]
@diachedelic the Payment Request Button relies on the Payment Request API which is not meant to be exposed in a webview: https://github.com/GoogleChromeLabs/payment-request-shim#current-interventions.

Your alternatives are a native implementation or kicking out to the browser: https://stackoverflow.com/questions/55869022/android-chrome-webview-access-to-google-pay-is-not-working

**Comment by JoshuvaGeorge03** [comment]
I had this similar issue, After some searching I have found out this. I thought it maybe useful for some. I have summarized my search findings below.

1) If you want to use Google Pay via a mobile app, you should use a native implementation, such as that offered by Stripe, or use a browser intent from your Android app to open the mobile Chrome browser.

2) You can implement chrome custom tabs or browser intents.

3) Google pay Api frequently asked question sections. 

Does the Google Pay API integration work in WebViews?
For Android apps which use WebViews, you must invoke native Android Google Pay APIs. See Binding JavaScript code to Android code for examples. (https://developers.google.com/pay/api/web/support/faq)

**Comment by Qiuzhuang** [comment]
> @diachedelic the Payment Request Button relies on the Payment Request API which is not meant to be exposed in a webview: https://github.com/GoogleChromeLabs/payment-request-shim#current-interventions.
> 
> Your alternatives are a native implementation or kicking out to the browser: https://stackoverflow.com/questions/55869022/android-chrome-webview-access-to-google-pay-is-not-working

is this updated in newest react-native webview?

> https://stackoverflow.com/questions/55869022/android-chrome-webview-access-to-google-pay-is-not-working

The recent webview has option enableApplePay for apple pay and it works. What can we do to google pay? Any update on this?

**Comment by ForeverLover** [comment]
> > @diachedelic the Payment Request Button relies on the Payment Request API which is not meant to be exposed in a webview: https://github.com/GoogleChromeLabs/payment-request-shim#current-interventions.
> > Your alternatives are a native implementation or kicking out to the browser: https://stackoverflow.com/questions/55869022/android-chrome-webview-access-to-google-pay-is-not-working
> 
> is this updated in newest react-native webview?
> 
> > https://stackoverflow.com/questions/55869022/android-chrome-webview-access-to-google-pay-is-not-working
> 
> The recent webview has option enableApplePay for apple pay and it works. What can we do to google pay? Any update on this?

Any solution for google pay via paymentrequestbutton in android webview?I have a similar situation with your question.Thanks for your answer.I'm glad to receive your futher info for this.

**Comment by damdeez** [comment]
I think Stripe should add this to their documentation for Payment Request Button to make it more clear to others here: https://stripe.com/docs/stripe-js/elements/payment-request-button?html-or-react=react
