### ISSUE TITLE
The "Google pay" button is not displayed on desktop browsers

### ISSUE THREAD

**Issue by NeeONCorp** [stripe/stripe-payments-demo#47]
Hi! I have a payment method in my google account, but when I go to [this page](https://stripe.com/docs/stripe-js/elements/payment-request-button) from the Google Chrome browser - the "Google pay" button is not displayed.

When I go to the same page from the phone (from the same Google account) the button is successfully displayed. what could be the problem?

**Comment by thorsten-stripe** [comment]
Please note that this issue tracker is for bugs or issues directly related to this project, and not for general support. Please feel free to reach out to https://support.stripe.com/email and we would be glad to help further!
