### ISSUE TITLE
"Invalid value for paymentRequest()" when specifying "CN" (which is valid country in UI)

### ISSUE THREAD

**Issue by nateritter** [stripe/stripe-payments-demo#5]
**What I did**

* copied the `.env.example` to a `.env` file and added my Stripe API details
* edited the `config.js` with `country: 'CN',` and `currency: 'cny',`
* ran `npm install` (successfully)
* ran `npm run start` (successfully)
* loaded the "App URL" page given from the `npm run start` command results in my browser (Chrome 64 with dev tools)

**What happened**

(1) The following console error appeared:

```
Uncaught (in promise) Error: Invalid value for paymentRequest(): country should be one of the following strings: AT, AU, BE, BR, CA, CH, DE, DK, EE, ES, FI, FR, GB, HK, IE, IN, IT, JP, LT, LU, LV, MX, NL, NZ, NO, PH, PL, PT, RO, SE, SG, SK, US. You specified: CN.
    at new t ((index):1)
    at $e ((index):1)
    at t ((index):1)
    at new t ((index):1)
    at e.<anonymous> ((index):1)
    at e.paymentRequest ((index):1)
    at payments.js:85
    at <anonymous>
```

(2) The "Country" field defaulted to the "United States" value

**What I expected**

(1) No console error
(2) Ability to choose "CN" as a country, considering that is the option value used in the select option for "China".
(3) The "Country" field to be defaulted to "China"

**Comment by romain-stripe** [comment]
Thanks for much @nateritter for reporting this issue! Indeed, `stripe.paymentRequest()` requires the two-letter country code of your Stripe account as [documented here](https://stripe.com/docs/stripe-js/reference#stripe-payment-request). It can only be one of the supported countries listed in https://stripe.com/global, which is different from the customer country.

I just added another `country` option for Stripe in `config.js` in commit b847d57a5d897aa3ef411aaaffa5b4c121bd2e35 which should solve the error you noticed; you can keep "US" or edit with your Stripe account country code.

I'm now closing this issue but feel free to reopen if you're still encountering any issues with Payment Request!

Thanks,
Romain
