### ISSUE TITLE
How to add the remaining of the 135+ countries?

### ISSUE THREAD

**Issue by mostafachatillon** [stripe/stripe-payments-demo#55]
Hello, I want to add all the 135+ countries to the menu. How can I do it?

**Comment by thorsten-stripe** [comment]
You can extend the select element here: https://github.com/stripe/stripe-payments-demo/blob/master/public/index.html#L57

Or via an API, e.g. https://github.com/apilayer/restcountries

Please note that this issue tracker is for bugs or issues directly related to this project, and not for general support. Please feel free to reach out to https://support.stripe.com/email and we would be glad to help further!
