### ISSUE TITLE
Proper way to setup stripe products and skus?

### ISSUE THREAD

**Issue by joshbedo** [stripe/stripe-payments-demo#68]
Noticing that the setup script is pretty inconsistent and would much rather have it as a one off script to run instead of something that runs every time you run the server. Current implementation seems really buggy. I just went to the site it setup the products, i refresh and now the page doesnt load and server says "already in progress...". It also seems like whenever i change the stripe product info everything breaks. I've had to wipe all my stripe test data 10 times now.

**Comment by thorsten-stripe** [comment]
Thanks for the feedback, @joshbedo, very fair point, today it's pretty tightly coupled to the demo products in the setup script. 

For Node it's pretty easy turning it into a one off setup script and adding it to the package.json file. I'll take that. I just need to figure out what's the best way for the other server implementations to do this, where node & npm might not be installed.

**Comment by joshbedo** [comment]
could you use the package.json's `postinstall` so it runs after `npm i` lots of places like heroku use that as a build command when deploying.
