### ISSUE TITLE
Danish postcodes are 4 digits - not 5

### ISSUE THREAD

**Issue by LarsBuur** [stripe/stripe-payments-demo#71]
Haven´t checked the source, but the demo required me to put in a 5 digit postcode/zipcode for Denmark and that is incorrect.

**Comment by thorsten-stripe** [comment]
Did you use the Danish test card (4000002080000001) from the docs[0]? The main test cards shown in the demo are US issued and therefore require a US postal code.

Closing this out as using the danish test card seems to work as expected. Please reopen if you think that's incorrect.

[0] https://stripe.com/docs/testing#international-cards

**Comment by LarsBuur** [comment]
Thanks - I did use the generic 4242 4242 4242 4242 test card.
