### ISSUE TITLE
Any way to link cart items? /payment/:sku

### ISSUE THREAD

**Issue by joshbedo** [stripe/stripe-payments-demo#72]
So i'm planning on using this demo as the checkout page. I have a landing page with pricing tiers/options and when they select an option i want to be able to add the plan they select to the cart. Immediately thought it would be cool if we could  maybe just pass a sku id or something so it knows which item to add. Right now i just have the setup products being added to cart every time and sometimes one of them is even added twice for no reason.

**Comment by thorsten-stripe** [comment]
Closing this out as I think this is out of scope for this demo. The demo is meant to showcase how to integrate various different payment methods with Stripe, but is not meant to be used in production.
