### ISSUE TITLE
After successful checkout have /payment?success=true flag or /payment/success page for marketing events

### ISSUE THREAD

**Issue by joshbedo** [stripe/stripe-payments-demo#73]
If you're ever selling online you typically want to install things like a Facebook/Google Pixel to track conversion events and optimize for certain objectives. Generally, you can place a little javascript on the thank you page to trigger a 'purchase' conversion with the value but with the way this is project is setup you can't really do anything like that without placing it somewhere in one of the route controller methods on the server-side which isn't ideal. Wondering if having a thank you success route is something easily doable?

**Comment by thorsten-stripe** [comment]
Closing this out as I think this is out of scope for this demo. The demo is meant to showcase how to integrate various different payment methods with Stripe, but is not meant to be used in production.
