### ISSUE TITLE
Question: Could you update this example for Strong Customer Authentication?

### ISSUE THREAD

**Issue by pmochine** [stripe/stripe-payments-demo#77]
Hey @stripe :)

I just read about SCA and I'm scared a bit... haha. Ok but now serious, wouldn't it be great when this example is SCA proof? I didn't check the code for a long time, maybe you even changed the code so it's set for the future.

Thanks :D

**Comment by thorsten-stripe** [comment]
@pmochine It already is :) You can see the changes that were needed here:
* https://github.com/stripe/stripe-payments-demo/pull/33/files
* https://github.com/stripe/stripe-payments-demo/commit/37caff051bf03cd9da87edb6b4b5c285d64f197d

**Comment by pmochine** [comment]
@thorsten-stripe oh how perfect! Thanks!
