### ISSUE TITLE
Error handelling on submit button

### ISSUE THREAD

**Issue by perrinewton** [stripe/stripe-payments-demo#80]
Hello, When you fill in the form to pay and don´t fill in the complete postal code and hit the pay button, you get correctly a message saying the postal code is incomplete, however the status of the pay button keeps saying processing all the time. I completed the postal code and waited a while and nothing happened, then I clicked the processing button again and payment was done (saw in stripe account) however ever got success message.

**Comment by thorsten-stripe** [comment]
Thanks for flagging but I'm not able to reproduce this[0]. If you're still facing this issue, please reopen with detailed steps to reproduce.

[0]
![image](https://user-images.githubusercontent.com/23213994/62378090-f040fe80-b53b-11e9-946f-66fb5aa13362.png)
