### ISSUE TITLE
500 error on php version

### ISSUE THREAD

**Issue by perrinewton** [stripe/stripe-payments-demo#81]
Hello, I have installed the php version several times and both the same. On previewing at localhost or Ngrok there is a 500 error on products, in Store.js on line 72

**Comment by youssef-stripe** [comment]
Hello!

Line 72 in store.js is where the products to be displayed are retrieved from the backend. The backend sends a GET request to retrieve the products from the account based on their skus. If not returned (non existing), they are created on the fly. Having a 500 error at that stage means that we are either unable to retrieve the products or to create them altogether.
Do you have your PHP logs so we can determine which is it and why this is happening?

I tried to reproduce with both an existing account and a new one but no error 500 in either case which makes me think there might be a conflict with the account you are using.
I'll know more once I have the logs.

**Comment by perrinewton** [comment]
Sorry, I searched but have no one.
No idea, I just installed following the instructions, as a matter of fact did not know the demo products automatically gets installed on my account as did not check settings page, and have ever used products.
In any case I will not use this demo as didn't know it was only for having products.

**Comment by youssef-stripe** [comment]
The products part is just to have something to display on the side for the purchase.
The main purpose of the demo is to showcase how the PaymentIntent API works with different payment methods.

Taking a blind guess: did you correctly configure your settings.ini file?

**Comment by perrinewton** [comment]
I suppose I did not configure it correctly, I tried both the node and php version.
I commented out the products on setting file and deleted on Stripe account and managed to display on page my product, however when entering Stripe my product was registered as a product. Really didn't see how to eliminate and not use the products with Stripe as I sell services not products. I quite liked the demo though.

Thanks,

**Comment by youssef-stripe** [comment]
The Products API is used by this project for demo purposes only. It is not a requirement to use our Payments API.

If you sell a service, you can integrate the PaymentIntent API: https://stripe.com/docs/payments/payment-intents/quickstart
If you have a subscription-based model, you can use our Billing solution: https://stripe.com/docs/billing/subscriptions/creating

As this is not an issue with the project itself, I'll go ahead and close this for now. Feel free to reach out to us for additional support: https://support.stripe.com/email
