### ISSUE TITLE
Facebook / Instagram Apple Pay doesn't button doesn't load

### ISSUE THREAD

**Issue by Nav31** [stripe/stripe-payments-demo#84]
When using the demo in the "in app browsers" of the Facebook and Instagram mobile apps, the Apple Pay button does not load.  However, it does load when using in-app browsers of different companies such as Twitter and Slack.
So I'm wondering if this is a bug, or is this intended behavior.  If this is intended behavior, why? 

Thanks!

**Comment by thorsten-stripe** [comment]
Apple Pay only works in Safari or an SFSafariViewController webview, therefore the functionality being available depends on how the corresponding app has implemented the in-app browser.

**Comment by Nav31** [comment]
Thanks @thorsten-stripe

**Comment by jhk115** [comment]
Hi @thorsten-stripe any plans to bring it to WKWebView as well?

**Comment by hofman-stripe** [comment]
Stripe.js should now supports Apple Pay in any WKWebView where Apple Pay is supported.

**Comment by jhk115** [comment]
Thanks for the response @hofman-stripe! We're not seeing it on Instagram's webview. IIRC, iOS discourages implementation of the web views to WKWebView or SFSafariViewController. Do you know if Facebook is rolling its own in-app browser?

**Comment by hofman-stripe** [comment]
I believe most of those in-app browsers do too much integration with the WKWebView, and Apple disables Apple Pay in those.

If you find any WKWebView where [Apple's own demo](https://applepaydemo.apple.com/) works but Stripe.js doesn't, please let us know.

**Comment by ren6** [comment]
Apple Pay works fine in WKWebView, seems like Facebook/Instagram app still use UIWebView
