### ISSUE TITLE
Refused to load the image '<URL>' because it violates the following Content Security Policy directive: "img-src 'self' <URL>".

### ISSUE THREAD

**Issue by justlearntutors** [stripe/stripe-payments-demo#89]
Error found on Stripe Payments Demo
Refused to load the image 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAE2klEQVRYR73Xf0zUZRwH8Pfne3cEKaFotfw1poUMQjnvIDFADrM8Wmy01kaOJBSUa/00QV1uznIJ2caGuhljSb+2ZvNHsKSZcMgRmsM7TGkopS5daoNO9FKO+z6f9nw5FH8h4MHz3/e52+fzus/zPJ/ne5Q/zzSDoYaTTv+28F7/4LLi7trZdO4aRmlQXrKpjQiRYL4EoJKJu6CK3eWNLSdGw0Ar5sZFcJB+DTPny4QM2IkQNulgs3k9IEYaQf4EtDzJVM8KkrVnxhUVqrWiwdU4WgDkJMZGGfRBLUQI8ie9ChUZnzc2140koq8CWo7cpNjpegoaR6REMNQvwaQw86vljqPVI4W4BdA/yZsp5vQe5j1yTmU1p8Lh+nYkEPcEyGQrkozZrOgqmQUz+N3yBmdZoBEDAjTEfHOhEFys7U3GunJH88e3I/jZm...YtGTJAW07LHBO83R/BmLAIOTZCxJPaTSWPX9qSXLT+8Sc+W1OIxelWfPdjDUpLilE5nhCpnc5blqJ9WIC+EJw8OwFClCJneSJeXix/EVYWb0ZcTDSyX7Rit70etnUboOh1eM7AqHzk9ldMPv9AAK0aqdCjJ+YHlGy3IjK6d/cLgZpDh7B09YdaVUKJsSdMIOqOCojqBwb0IuLi8EyKE6v9rwrebtg2FmOvvR7BYOwKE5gtk/fPJpcMZA0IoBdhPI6Z0TFoPwl4u3FV0WGtR8HrIQyz/o61l5XaQ7XNsksGZnCqsQhEmwYVjXAKnZ0J5DrjDiDANBEQp0E0dmAE/QVWU8juOjOsTjhQcE4zrgbTJ/f8DvM5GDiN9rtODbsVDwgAdEg1VoNo0a3nXe43PgFVfYkOHjvd/7OALcGN3pA4JQTBj5cBvASAHuDLYNqC7ksb6S7/ugMOuAmJDofOMBEXPGepvb37XpX7H1O/3hQof8a0AAAAAElFTkSuQmCC' because it violates the following Content Security Policy directive: "img-src 'self' https://q.stripe.com".

Screenshot
![stripe-error](https://user-images.githubusercontent.com/39218132/62703895-7fda2780-b9ea-11e9-8dae-caa44582fc6d.JPG)

**Comment by thorsten-stripe** [comment]
@justlearntutors thanks for reporting, but I'm not able to reproduce this on my end. Can you share your browser/user agent details?

**Comment by justlearntutors** [comment]
I am using the newest version of Chrome.

Other people have the same error. https://stackoverflow.com/questions/35489518/stripe-checkout-css-content-policy-error

**Comment by thorsten-stripe** [comment]
Do you have any extensions or ad blockers, etc. that might be modifying the CSP? The issue on Stackoverflow, while having a similar error message, does not seem related to this.

Closing this out as I don't think it is an issue with this project. If this is causing issues for you, please to reach out via https://support.stripe.com/email

**Comment by justlearntutors** [comment]
I had installed a Chrome extension. When I removed the extension, it worked.

**Comment by malcolmocean** [comment]
I'm getting this on Brave, fwiw.

**Comment by danieltorscho** [comment]
> fwiw

what "fwiw" means ?

**Comment by barrymcgee** [comment]
> what "fwiw" means ?

"For what it's worth" - this phrase is used to signify the previous sentence may be insignificant but the person is saying it anyway in case it has value.

**Comment by oaustegard** [comment]
> I had installed a Chrome extension. When I removed the extension, it worked.

@justlearntutors do you recall which extension this was? I am encountering the same issue (for github, not stripe) and having trouble tracking it down
