### ISSUE TITLE
Google Pay button doesn't show up

### ISSUE THREAD

**Issue by swrobel** [stripe/stripe-payments-demo#9]
On the [demo site](https://stripe-payments-demo.appspot.com/), the Google Pay button doesn't show up in Chrome on Android. I'm able to see & use it on Googles [demo site](https://emerald-eon.appspot.com/).

**Comment by thorsten-stripe** [comment]
@swrobel can you provide screenshots? It's working fine for me. Also please note that the button won't be Google branded, but Google Pay is implemented via the "Pay Now" button which uses the payment request API which allows for selection between Google Pay or cards stored on the device: 
![image](https://user-images.githubusercontent.com/23213994/38427601-984853ec-39b1-11e8-9fd7-d840dfc21d01.png)

**Comment by jenan-stripe** [comment]
That demo site also doesn't use `canMakePayment`, but Stripe's integration does. You'll need to [add a card to Chrome](https://support.google.com/chrome/answer/142893?co=GENIE.Platform%3DDesktop&hl=en) for the Stripe button to show up.

**Comment by swrobel** [comment]
@thorsten-stripe and why does it use that weird button instead of a branded one...?

**Comment by thorsten-stripe** [comment]
@swrobel can you be more specific regarding what you mean with "that weird button"?

We provide a default "Pay Now" button that indicates a native browser checkout, where Google Pay is available within the payment sheet on supported devices. You can customize that default button to a certain extend[0]. Alternatively you can design your own button and open the payment sheet in that button's click handler[1]. (Note that the show method must be called as the result of a user interaction, e.g. the click of your custom button). 

Not showing a single branded button is intentional here as the goal of the payment request standard is to reduce the sea of buttons on merchant sites. End customers will still see their preferred wallet/brand logo once the payment sheet opens.

If you prefer to integrate directly against the Google Pay API, you can follow Google’s instructions[2].

[0] https://stripe.com/docs/stripe-js/elements/payment-request-button#styling-the-element
[1] https://stripe.com/docs/stripe-js/reference#payment-request-show
[2] https://developers.google.com/pay/api/web/setup

**Comment by swrobel** [comment]
This button:
<img width="348" alt="screen shot 2018-04-09 at 11 34 12 am" src="https://user-images.githubusercontent.com/157270/38515749-f53f8392-3be9-11e8-8917-61ef78dd354a.png">

**Comment by thorsten-stripe** [comment]
@swrobel yes, this is the beautifully crafted button we provide by default ;) Let us know any feedback you might have regarding the button!

If it currently doesn't fit your needs, you can resort to the alternatives listed above. Hope this helps :)

**Comment by swrobel** [comment]
Sorry, I guess the confusion is just that the Apple Pay button that users recognize shows up on those devices, but feedback I've gotten from Android users is they have no idea what that button means or will do and hence are less likely to click it. Just some feedback.

**Comment by thorsten-stripe** [comment]
Thanks for the feedback! I'll share it with the team 👍

**Comment by swrobel** [comment]
Didn't mean to insult the button. I do personally find it beautiful :)

**Comment by thorsten-stripe** [comment]
Thanks, we appreciate that, and we very much appreciate your feedback, which is very valid and helpful as we work on the next iteration of what we call "The Button" :)

**Comment by atty-stripe** [comment]
@swrobel to share some context, the [Payment Request API](https://stripe.com/docs/payment-request-api) is a cross-browser standard that allows websites to request payment information from the user, across a set of payment methods. This can include credit cards stored in the browser, Google Pay / Microsoft Pay / Apple Pay, and any other future payment methods a browser (or a [payment handler](https://www.w3.org/TR/payment-handler/#dfn-payment-handler)) might implement. As a result, since this API abstracts multiple payment methods, it's hard to show a single branded button. 

The brand, however, is exposed once the user clicks on the button and the browser dialog lets the user pick between their multiple payment methods (as seen in the screenshot above.)

Hope that illustrates why there's one button to abstract away the notion of "pay with payment method stored / known to your browser".

**Comment by gbutt** [comment]
I had an issue where the Pay Now button wouldn't show, but it was very niche. Here are the details:

- My stripe form is itself served within an iframe with attribute allowpaymentrequest="true".
- I created the payment request instance within an IIFE.
- Everything works fine when I load the form directly, but when I load the form in the iframe the call to canMakePayment resolves null.

```js
(function(){
  var paymentRequestInstance = stripe.paymentRequest({...});
  paymentRequestInstance.canMakePayment().then(function(result) {
    // result is null
  });
})();
```

**Solution**: I saved the payment request instance onto the window object.
```js
(function(){
  window.paymentRequestInstance = stripe.paymentRequest({...});
  paymentRequestInstance.canMakePayment().then(function(result) {
    // result is {applePay: false}
  });
})();
```

Very niche, hope this helps someone else having the same issue.

**Comment by atty-stripe** [comment]
@gbutt that seems odd, and not something we'd expect to happen.

Here's an example of using our Payment Request Button within an iframe (the result is rendered inside jsfiddle's iframe, which has `allowpaymentrequest=true`): https://jsfiddle.net/attystripe/r5jky2uy/.

Could you share a minimal reproduction of the bug?

**Comment by nxmohamad** [comment]
@gbutt I'm facing the same issue whereby result is null, but saving to window object doesn't solve it for me. still null.

**Comment by naveennavi** [comment]
@atty-stripe thanks to sharing your code for the stripe payment request. I have executed your code without angular build it will work fine but I will execute your code via angular it will not be showing button in my chrome browser but It's working on my mobile. Even touch screen laptop browser also not showing button. Kindly help me

**Comment by thorsten-stripe** [comment]
@naveennavi sorry to hear about this issue. Please note though that there is no active support provided via issues on this repo. Can you please reach out to support using the form at https://support.stripe.com/ (preferred) or via email to support@stripe.com.

**Comment by ajlond123** [comment]
> @swrobel to share some context, the [Payment Request API](https://stripe.com/docs/payment-request-api) is a cross-browser standard that allows websites to request payment information from the user, across a set of payment methods. This can include credit cards stored in the browser, Google Pay / Microsoft Pay / Apple Pay, and any other future payment methods a browser (or a [payment handler](https://www.w3.org/TR/payment-handler/#dfn-payment-handler)) might implement. As a result, since this API abstracts multiple payment methods, it's hard to show a single branded button.
> 
> The brand, however, is exposed once the user clicks on the button and the browser dialog lets the user pick between their multiple payment methods (as seen in the screenshot above.)
> 
> Hope that illustrates why there's one button to abstract away the notion of "pay with payment method stored / known to your browser".

In that case why is it possible to show the Apple Pay button reliably but not Google Pay? Is this something that Stripe may support in the future? The ability for `canMakePayment` to return an object with `applePay` and `googlePay` defined as booleans indicting whether they're enabled.

**Comment by thorsten-stripe** [comment]
@ajlond123 Apple Pay is built natively into Safari, and therefore is only available within Safari browsers whereas Google Pay (if not done via PRAPI) is a JavaScript library that works across browsers.

We are working with Google to get this resolved but can't yet share a timeline for it.

**Comment by ajlond123** [comment]
@thorsten-stripe - Thanks for the update.

**Comment by usman10scorpio** [comment]
I am making a custom button, and I want to show GPay image in my button on chrome firefox etc and applyePay image on firefox. Is there a smart way to cater this in css or should go for this [answer](https://stackoverflow.com/questions/49328382/browser-detection-in-reactjs) ?. As I am making the app in react.

**Comment by JoshuvaGeorge03** [comment]
I have google pay in my device, but still it says no saved cards for you account. Please advice

**Comment by usman10scorpio** [comment]
> I have google pay in my device, but still it says no saved cards for your account. Please advice

Open the demo site in your mobile device if you see the pay now button ( on android - chrome/firefox ) or apple pay button in iOs ( safari ) then there must be some mistake in your code implementation. 

If not then for windows/android ( chrome / firefox ) go to setting and in payments, add test card and see if you see the PAY NOW button now. 

For APPLE PAY you should have a real test card in wallet. If still you dont see the button try changing your location apple pay is not supported in every country. 

I hope my comment will help you. I faced similar issues like you and applied the above methods.

**Comment by fpilee** [comment]
I can see the Google Branded BTN in Stripe Checkout page, but using Payment Request Btn I get Pay Now Btn. Is this correct?

**Comment by usman10scorpio** [comment]
> I can see the Google Branded BTN in Stripe Checkout page, but using Payment Request Btn I get Pay Now Btn. Is this correct?

Yes man

**Comment by rchrdnsh** [comment]
I currently do not see either the 'G Pay' button or a more generic 'Pay Now' button anywhere and in any way and in any capacity for my stripe react elements form or for ANY stripe elements or checkout examples created by stripe. The 'Apple Pay' button works great everywhere it is supported, but the payment request button and or 'G pay' button does not work for my form or ANY stripe example form for me at the moment...I have tried to check my payment settings in chrome but they seem to be correct, so i don't know what's up...any updates in regards to working with google on this?

**Comment by xalunda** [comment]
Why is this closed? 
Why can't we get the official GPay button?
I don't get it.

**Comment by barrymcgee** [comment]
> I've gotten from Android users is they have no idea what that button means or will do and hence are less likely to click it. Just some feedback.

@swrobel  On a payment page, Android users have no idea what a button saying "Pay now" means? For real?

**Comment by layflags** [comment]
The Google Pay button doesn't show up anymore in mobile Chrome for a few days now in our web app with Stripe Checkout integration. On Desktop Chrome on Mac it shows up most of the time. I tried to reset the Browser settings, but this doesn't help. Was there a change deployed recently that causes this behaviour? 

As a reference just open the following link and hit the "Donate now" button: https://www.thanku.social/en/app/donate?currency=EUR&donateeGroup=CleanOcean&price=1

**Comment by aseem-hegshetye** [comment]
I tried both test mode and live mode  on (chrome, firefox ) ubuntu. I dont see google pay on stripe checkout page. 
I tried the same url on safari on iphone. I did not see apple pay there either.

**Comment by katsar0v** [comment]
Android user here... using the standard stripe plugin for WooCommerce, I see no buttons on my phone unfortunately :( (Google Pay is installed and is setup)

**Comment by Eliyas** [comment]
Hello Everyone.
Try enable these options. It worked for me.

go to  => chrome://settings/payments?search=Google+Pay+
enable => Allow sites to check if you have payment methods saved 
Also you should have saved a card payment in you payment methods.
https://pay.google.com/gp/w/u/0/home/paymentmethods
![image](https://user-images.githubusercontent.com/14360796/130312604-70801d7a-1f07-4f17-8d8c-2c8bcc23f89f.png)

**Comment by Nikita-Burd** [comment]
I want to know that if google pay and apple apple both can be seen at a time on apple devices
