### ISSUE TITLE
Issue with SetupIntents API, client_secret is not accepted

### ISSUE THREAD

**Issue by nickzam** [stripe/stripe-payments-demo#97]
Hi,

I am working on migration to PSD2. Following migration guide as mentioned here: https://stripe.com/docs/payments/payment-intents/migration#saving-cards
Because we need to save cards for later charges I am using SetupPaymentsIntent flow.
I've created a setup intent key on server and passing it to client. Consider that client_secret key starts with "seti_", so it's SetupIntents key.

On the client I call handleCardSetup like this

```javascript
var additionalInfo = {
            payment_method_data: {
                billing_details:  {
                   name: accountOwner,
                   email: user.email
                }
            },
            metadata: {
                user_id: user.id
            }
        }
        stripe.handleCardSetup(client_secret, card, additionalInfo);
```
where card is CardElement; 
accountOwner, user.email and user.id are a part of user object and contain proper values.
Chrome console shows no js errors.

I am always receiving back current error: 

`IntegrationError: Invalid value for stripe.handleCardSetup intent secret: value should be a client secret of the form ${id}_secret_${secret}. You specified: "seti_1FCkP2DCVFfL6ds8iNrfLtLM_secret_FiAkqrqJ99O2aDnPwt73qtKKbs2ZuSY".`

I've checked that client secret is the same on server side and client side.

Could you please help me understand what is wrong here?

It would be great to have a demo for SetupIntents somewhere.

**Comment by thorsten-stripe** [comment]
@nickzam can you please reach out to support using the form at https://support.stripe.com/ (preferred) or via email to support@stripe.com ideally including the `req_id` returned by the `handleCardSetup` confirm network request (can be found in the Chrome dev tools network tab).

You can find a SetupIntent demo here: https://github.com/stripe-samples/saving-card-without-payment

**Comment by lborgman** [comment]
I have a similar issue. Please reopen this. The suggested client secret format is nowhere near the keys you provide.

**Comment by thorsten-stripe** [comment]
This project makes only single/guest transactions and therefore does not interface with SetupIntents. For SetupIntents, please refer to this sample: https://github.com/stripe-samples/saving-card-without-payment and if you're running into an issue, please contact our support team with more details.
